# -*- coding: utf-8 -*-
"""all models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEhAIdXbtkzdM-PA5qJlkUClFbZrXI8t
"""

!pip -q uninstall -y transformers bitsandbytes accelerate
!pip -q install -U \
  "transformers==4.52.4" \
  "bitsandbytes>=0.46.1" \
  "accelerate>=1.6.0" \
  sentencepiece \
  tiktoken \
  einops \
  tqdm \
  huggingface_hub

!pip -q install "pandas==2.2.2"

!pip -q install -U \
  "transformers>=4.51.0" \
  "bitsandbytes>=0.46.1" \
  accelerate \
  sentencepiece \
  tiktoken \
  einops \
  tqdm \
  pandas \
  transformers_stream_generator

from huggingface_hub import login
from getpass import getpass

hf_token = getpass("Paste your Hugging Face token: ")
login(token=hf_token, add_to_git_credential=False)

import os
import re
import gc
import math
import json
import shutil
import warnings
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional

import torch
import torch.nn.functional as F
import pandas as pd
from tqdm.auto import tqdm

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig
)

warnings.filterwarnings("ignore")

# ============================================================
# 0. 全局设置
# ============================================================

# 建议把 HF cache 放到 Drive；如果 Drive 空间有限，可改为 "/content/hf_cache"
HF_HOME = "/content/drive/MyDrive/hf_cache"
os.environ["HF_HOME"] = HF_HOME
os.environ["TRANSFORMERS_CACHE"] = HF_HOME
os.makedirs(HF_HOME, exist_ok=True)

OUTPUT_DIR = "/content/drive/MyDrive/surprisal_results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# 默认用 mean surprisal 判断句子偏好，避免短句天然总 surprisal 更低
DECISION_METRIC = "mean"  # 可选: "mean" 或 "sum"

# 默认 4-bit；如果你拿到 A100 且只跑 7B/8B，也可以改成 "none"
DEFAULT_QUANT = "4bit"    # 可选: "4bit", "8bit", "none"

# MacBERT 只是 CSC baseline，不是 surprisal 必需项。建议先 False。
RUN_MACBERT = False

# 若想快速测试，把这里设成 True，只跑前 3 条
DEBUG_SMALL = False
DEBUG_N = 3


# ============================================================
# 1. 数据解析
# ============================================================
raw_data_ba = """
(情况 1：物理状态改变)
例1： 那个苹果坏了，我……（把它扔了✅）/（扔了它）。
例2： 这杯牛奶太凉了，弟弟刚才……（把它加热了✅）/（加热了它）。
例3： 衬衫上有一块咖啡渍，我昨天……（把它洗干净了✅）/（洗干净了它）。
例4： 这块蛋糕太甜了，但我还是……（把它吃完了✅）/（吃完了它）。
例5： 刚才有一只蚊子，我一巴掌……（把它打死了✅）/（打死了它）。
例6： 桌子上的那张废纸，我……（把它撕了✅）/（撕了它）。
例7： 这个旧手机没用了，我准备……（把它卖了✅）/（卖了它）。
例8： 这封信是写给你的，我……（把它拆开了✅）/（拆开了它）。
例9： 那个花瓶快掉下来了，幸好我……（把它抓住了✅）/（抓住了它）。
例10： 这首曲子太吵了，我……（把它关了✅）/（关了它）。
例11： 我的旧电脑太慢了，昨天我……（把它换了✅）/（换了它）。
例12： 汤里掉进了一只苍蝇，我只能……（把它倒了✅）/（倒了它）。
例13： 这张照片拍得不好看，我……（把它删了✅）/（删了它）。
例14： 那盘饺子不能剩下，弟弟刚刚……（把它吃掉了✅）/（吃掉了它）。
例15： 这个包裹的胶带太紧了，我……（把它剪开了✅）/（剪开了它）。
例16： 这件衣服破了一个洞，妈妈已经……（把它缝好了✅）/（缝好了它）。
例17： 那个面包已经发霉了，我早上……（把它丢掉了✅）/（丢掉了它）。
例18： 这碗汤实在太咸了，我加了一些水……（把它冲淡了✅）/（冲淡了它）。
例19： 厨房的窗户太脏了，我用抹布……（把它擦干净了✅）/（擦干净了它）。
例20： 这个西瓜太大了，我一个人吃不完，先用刀……（把它切开了✅）/（切开了它）。
例21： 那张画被妹妹涂得乱七八糟，我只能……（把它扔了✅）/（扔了它）。
例22： 昨天买的肉还没吃，为了保鲜，我先……（把它冻起来了✅）/（冻起来了它）。
例23： 我的鞋子昨天淋湿了，我用吹风机……（把它吹干了✅）/（吹干了它）。
例24： 这个汉堡实在太大了，但我太饿了，最后还是……（把它吃光了✅）/（吃光了它）。
例25： 那封旧情书，他用打火机……（把它烧了✅）/（烧了它）。
例26： 这篇作文有很多错别字，昨天晚上我已经……（把那些字修改了✅）/（修改了那些字）。
例27： 墙上的那个钉子太危险，爸爸用锤子……（把它拔出来了✅）/（拔出它来了）。
例28： 弟弟的玩具车坏了，我花了一个小时才……（把它修好了✅）/（修好了它）。
例29： 锅里没有倒水，我不小心……（把它烧糊了✅）/（烧糊了它）。
例30： 那个旧纸箱没用了，我一脚……（把它踩扁了✅）/（踩扁了它）。
例31： 这条鱼腌好了，妈妈放进锅里……（把它炖了✅）/（炖了它）。
例32： 那个气球吹得太大了，弟弟拿针一戳就……（把它扎破了✅）/（扎破了它）。
例33： 头发太长了，我昨天去理发店……（把它剪短了✅）/（剪短了它）。
例34： 这张纸太大了，放不进信封，我只好……（把它折起来了✅）/（折起它来了）。
例35： 我的铅笔头断了，我用小刀重新……（把它削尖了✅）/（削尖了它）。
例36： 这个旧杯子有裂缝，我不小心……（把它打碎了✅）/（打碎了它）。
例37： 地上的那张废纸，我捡起来顺手……（把它扔了✅）/（扔了它）。
例38： 昨天晚上剩下的米饭，我早上加了蛋……（把它炒了✅）/（炒了它）。
例39： 这瓶矿泉水我已经打开了，你赶紧……（把它喝了吧✅）/（喝了它吧）。
例40： 那块大石头挡在路中间，工人们用机器……（把它砸碎了✅）/（砸碎了它）。
例41： 外面太阳很大，被子很潮湿，妈妈拿出去……（把它晒干了✅）/（晒干了它）。
例42： 这个木头椅子不结实了，爷爷用钉子……（把它加固了✅）/（加固了它）。
例43： 我的旧裤子太长了，昨天裁缝……（把它改短了✅）/（改短了它）。
例44： 这篇文章写得太长了，我就……（把它缩短了✅）/（缩短了它）。
例45： 那个旧轮胎漏气了，修车师傅……（把它补好了✅）/（补好了它）。
例46： 这杯茶已经凉透了，我不喜欢喝凉茶，就……（把它倒掉了✅）/（倒掉它了）。
例47： 听说你想吃饼干，我现在已经……（把它烤熟了✅）/（烤熟它了）。
例48： 弟弟把口香糖吐在纸巾里，他……（把它包起来了✅）/（包起它来了）。
例49： 那个闹钟一直响个不停，我伸手……（把它关掉了✅）/（关掉它了）。
例50： 这盒冰淇淋马上就要融化了，你快点……（把它吃了吧✅）/（吃了它吧）。

(情况 2：空间位移)
例1： 你的外套放在沙发上太乱了，我……（把它挂起来了✅）/（挂起它来了）。
例2： 外面下雨了，院子里的自行车，我已经……（把它推进来了✅）/（推它进来了）。
例3： 这本书我看完了，昨天我……（把它放回书架了✅）/（放它回书架了）。
例4： 垃圾桶满了，出门的时候我……（把垃圾扔了✅）/（扔了垃圾）。
例5： 行李箱太重了，我叫人……（把它搬上楼了✅）/（搬它上了楼）。
例6： 刚买的啤酒不凉，我……（把它放进冰箱了✅）/（放它进了冰箱）。
例7： 钱包掉在地上了，我……（把它捡起来了✅）/（捡起它来了）。
例8： 你的帽子掉在椅子下了，我……（把它拿走了✅）/（拿走了它）。
例9： 这些旧报纸没用了，我……（把它们丢到门外了✅）/（丢它们到门外了）。
例10： 黑板上的字写错了，老师……（把它擦掉了✅）/（擦掉了它）。
例11： 确认没有拼写错误之后，秘书走进经理办公室……（把那份重要文件递过去了✅）/（递过去了那份重要文件）。
例12： 弟弟对动物毛发过敏，所以妈妈只能……（把那只小狗抱出去了✅）/（抱出去了那只小狗）。
例13： 看到桌子上前女友的照片，他叹了一口气，然后……（把那张旧照片收了起来✅）/（收起来了那张旧照片）。
例14： 这个沙发挡住了门，我们……（把它移开了✅）/（移开了它）。
例15： 那只小猫在雨里很冷，我……（把它抱回家了✅）/（抱它回家了）。
例16： 这个抽屉太满了，我……（把不需要的东西拿出来了✅）/（拿出来不需要的东西了）。
例17： 刚买的鸡蛋怕摔碎，妈妈小心地……（把它放进了篮子里✅）/（放它进了篮子）。
例18： 地图太大了不好拿，我上车前……（把它卷起来了✅）/（卷起它来了）。
例19： 客厅的那个旧沙发，搬家公司今天早上已经……（把它运走了✅）/（运走它了）。
例20： 你的身份证落在我这里了，我明天下午……（把它送过去✅）/（送它过去）。
例21： 下班时间到了，他关上电脑，迅速地……（把那台电脑收进去了✅）/（收进去了那台电脑）。
例22： 那个大纸箱在路边太危险，环卫工人……（把它拖走了✅）/（拖走了它）。
例23： 这封挂号信很重要，邮递员准时……（把它放进了信箱✅）/（放它进了信箱）。
例24： 大家吃完晚饭后，懂事的妹妹主动帮忙，……（把那几个空碗端进去了✅）/（端进去了那几个空碗）。
例25： 那几本书实在太重了，我帮你……（把它们拿上车吧✅）/（拿它们上车吧）。
例26： 听到老师的脚步声，正在玩游戏的同学赶紧……（把那个手机藏起来了✅）/（藏起来了那个手机）。
例27： 办公室里的那台旧打印机坏了，刚才管理员……（把那台打印机搬走了✅）/（搬走了那台打印机）。
例28： 天气突然变热了，我……（把那件裙子拿出来了✅）/（拿出了那件裙子）。
例29： 快递员递给我一个大包裹，我就……（把那个包裹收下了✅）/（收下了那个包裹）。
例30: 课桌上堆了很多书，他为了腾出地方写作业，就……（把那几本书拿开了✅）/（拿开了那几本书）。
例31： 桌子上的书太乱了，我刚才……（把它们收起来了✅）/（收起它们来了）。
例32： 刚放学回家，他一进门就觉得非常累，马上……（把那个沉重的书包放下了✅）/（放下了那个沉重的书包）。
例33： 桌子上的这幅画很漂亮，爸爸决定明天……（把它挂起来✅）/（挂起它来）。
例34： 昨天天气非常晴朗，奶奶一大早就打开门，……（把那床厚被子抱出去了✅）/（抱出去了那床厚被子）。
例35： 口袋里的硬币掉出来了，我捡起来，又……（把它装回去了✅）/（装它回去了）。
例36： 墙角的那盆花因为没有阳光快要枯萎了，我赶紧……（把那盆花移出来了✅）/（移出来了那盆花）。
例37： 这盆花需要阳光，今天早上我……（把它搬到阳台上了✅）/（搬它到阳台上了）。
例38： 银行卡掉在了沙发缝里，我找了半天，终于伸手……（把那张银行卡拿出来了✅）/（拿出来了那张银行卡）。
例39： 抽屉里的那份合同很重要，我……（把它拿出来了✅）/（拿出它来了）。
例40： 厨房里的垃圾味道太大了，我早上出门去上班时顺便……（把那袋垃圾带出去了✅）/（带出去了那袋垃圾）。
例41： 门口的那袋垃圾发臭了，我上班时顺手……（把它带下楼了✅）/（带它下楼了）。
例42： 这些明信片是给朋友的，我明天去邮局……（把它们寄出去✅）/（寄出去它们）。
例43： 今天外面的阳光特别好，爷爷走到客厅，慢慢地……（把那把旧椅子搬出去了✅）/（搬出去了那把旧椅子）。
例44： 护照是非常重要的东西，你一定要……（把它收好✅）/（收好它）。
例45： 黑板擦不见了，原来是有同学下课后……（把它拿走了✅）/（拿走它了）。
例46： 冰箱门没关紧，我走过去轻轻地……（把它推上了✅）/（推上了它）。
例47： 那个大纸箱挡在走廊中间，非常危险，我叫同事帮忙……（把那个大箱子推开了✅）/（推开了那个大箱子）。
例48： 这个广告牌在路边很容易挡住视线，警察昨天……（把它拆下来了✅）/（拆下它来了）。
例49： 盘子里的那些菜太远了，你能帮忙……（把它端过来吗✅）/（端它过来吗）？
例50： 你的外套掉在客厅地上了，我顺手……（把它挂到门后了✅）/（挂到门后了）。
"""

raw_data_svo = """
(情况 1：习惯性动作与泛指)
例1： 弟弟非常喜欢运动，每天下午都去操场……（踢足球✅）/（把足球踢了）。
例2： 老板每天到办公室以后，都会先在桌子前……（喝咖啡✅）/（把咖啡喝了）。
例3： 她很喜欢阅读，她回家的第一件事就是坐在沙发上……（看书✅）/（把书看了）。
例4： 每天中午十二点，工厂的工人们都会准时去食堂……（吃午饭✅）/（把午饭吃了）。
例5： 这所学校的管理很严格，老师要求学生们要大声地……（读课文✅）/（把课文读了）。
例6： 我平时不爱喝饮料，只……（喝白开水✅）/（把白开水喝了）。
例7： 为了准备下个月的考试，他每天在图书馆……（背单词✅）/（把单词背了）。
例8：每天晚上睡觉以前，我都去卫生间…… (刷牙 ✅ / 把牙刷了)
例9：每个周末去公园的时候，奶奶总在湖边…… (听歌 ✅ / 把歌听了)
例10： 弟弟不开心的时候，喜欢在房间里……（弹吉他✅）/（把吉他弹了）。
例11：每天早上吃早饭的时候，弟弟都会……（喝牛奶✅）/（把牛奶喝了）。
例12：每天早上六点起床后，爷爷常常坐在院子里……（听广播✅）/（把广播听了）。
例13： 每天下班回家后，爸爸总是习惯坐在沙发上打开手机……（看新闻✅）/（把新闻看了）。
例14：每天晚上睡觉前，妹妹都会坐在书桌前安静地……（写日记✅）/（把日记写了）。
例15：每个周末下午五点，邻居家的女儿都会在自己的房间里……（弹钢琴✅）/（把钢琴弹了）。
例16： 每次去超市，她习惯推着车子……（买零食✅）/（把零食买了）。
例17： 妈妈非常喜欢植物，每次去超市的时候，她都会顺便……（买鲜花✅）/（把鲜花买了）。
例18： 王老师平时不爱喝咖啡，他每天在办公室只……（喝绿茶✅）/（把绿茶喝了）。
例19： 为了学好汉语，他每天都坚持在练习本上……（写汉字✅）/（把汉字写了）。
例20： 经理每天早上到了公司，第一件事就是打开电脑……（查邮件✅）/（把邮件查了）。
例21： 每次坐地铁的时候，为了打发时间，我都会戴上耳机……（听音乐✅）/（把音乐听了）。
例22： 小区里有一位好心的阿姨，每天傍晚都会去花园……（喂流浪猫✅）/（把流浪猫喂了）。
例23： 这位护士很细心，每天都会按时给每个病人……（量体温✅）/（把体温量了）。
例24： 他的视力不太好，只要是看书或者看电脑，就一定会……（戴上眼镜✅）/（把眼镜戴上）。
例25： 那位经理很有责任心，每天上班第一件事就是在电脑前……（回邮件✅）/（把邮件回了）。
例26： 农民伯伯很辛苦，每天天亮就会去地里……（干农活✅）/（把农活干了）。
例27： 弟弟放暑假了，每天下午做完作业后，他都会用平板电脑……（玩游戏✅）/（把游戏玩了）。
例28： 每天幼儿园放学后，孩子们最期待的事情就是坐在电视机前……（看动画片✅）/（把动画片看了）。
例29： 为了促进消化，她每天吃完午饭半小时后，都会……（喝酸奶✅）/（把酸奶喝了）。
例30： 妈妈对烘焙很感兴趣。每个周末的早上，她都会在厨房里……（烤面包✅）/（把面包烤了）。
例31： 每个深夜，我都看见那位年轻作家在电脑前……（写小说✅）/（把小说写了）。
例32： 每个星期五晚上，她都会去电影院……（看新电影✅）/（把新电影看了）。
例33： 为了保持皮肤健康，她每天都要……（涂防晒霜✅）/（把防晒霜涂了）。
例34： 临近考试的时候，很多学生都会去图书馆……（复习功课✅）/（把功课复习了）。
例35： 每次去北京出差，他都会抽空去……（吃北京烤鸭✅）/（把北京烤鸭吃了）。
例36： 每天早上起床后，他都会在厨房……（做早饭✅）/（把早饭做了）。
例37： 天气热的时候，孩子们总是喜欢去海边……（吃冰淇淋✅）/（把冰淇淋吃了）。
例38： 每次遇到不会的汉字，他都习惯用手机……（查字典✅）/（把字典查了）。
例39： 只要是周末，爸爸都会坐在沙发上……（看报纸✅）/（把报纸看了）。
例40：每天下班回家路上，妈妈都会去菜市场……（买菜✅）/（把菜买了）。
例41： 每天吃完晚饭，全家人都会坐在客厅里……（看电视剧✅）/（把电视剧看了）。
例42：每天下班后，哥哥都会去健身房……（锻炼身体✅）/（把身体锻炼一下）。
例43： 每个月这个时候，妹妹都会去理发店……（剪头发✅）/（把头发剪了）。
例44： 每次放假，他们一家人都会去海边……（抓鱼✅）/（把鱼抓了）。
例45： 每当有空的时候，姐姐总喜欢在阳台上……（喂鸽子✅）/（把鸽子喂了）。
例46： 每天睡觉前，妈妈都会给孩子……（讲故事✅）/（把故事讲了）。
例47： 每天上课前，老师都会仔细地给学生……（批改作业✅）/（把作业批改了）。
例48： 每天开车前，司机都会认真地……（检查汽车✅）/（把汽车检查了）。
例49： 每到冬天，北方人常常一起……（吃火锅✅）/（把火锅吃了）。
例50： 遇到周末，很多年轻人都喜欢去酒吧……（喝酒✅）/（把酒喝了）。

(情况 2：叙述经历和日程)
例1： 昨晚停电了，我在黑暗中坐了一会儿，然后去厨房……（点了那根蜡烛✅）/（把那根蜡烛点了）。
例2： 我昨天复习得很认真，先看了书上的笔记，又默写了单词，然后……（做完了那张练习卷。✅）（把那张练习卷做完了。）
例3： 周末我去逛商场，买了一双鞋，晚上还……（看了一场电影✅）/（把那场电影看了）。
例4： 早上时间太紧了，我匆匆忙忙刷了牙，洗了脸，然后……（穿上了鞋子✅）/（把鞋子穿上了）。
例5： 昨天生日派对上，大家先唱了生日歌，又许了愿望，然后一起……（切了蛋糕✅）/（把蛋糕切了）。
例6： 他走进房间，脱下外套，然后走到窗前默默地……（点了一支烟✅）/（把那支烟点了）。
例7： 去北京旅行的时候，我们去了故宫，看了天安门，爬了长城，最后还……（吃了烤鸭✅）/（把烤鸭吃了）。
例8： 经理先开了一个早会，然后回到办公室，开始…… (写那份年终报告 ✅ / 把那份年终报告写了)
例9： 在音乐会上，大家都很安静，认真地…… (听那首钢琴曲 ✅ / 把那首钢琴曲听了)
例10： 到了海边，孩子们兴奋地脱掉鞋子，马上跑过去……（踩那些沙子✅）/（把那些沙子踩了）。
例11： 饭后，我帮妈妈洗了碗，然后看了一会儿电视，就回到自己房间里……（写作业了✅）/（把作业写了）。
例12： 昨天我去书店，先买了一本字典，然后去二楼……（买了一本画册✅）/（把那本画册买了）。
例13： 早上我起床后，先喝了一杯温水，然后去厨房……（吃了一块面包✅）/（把那块面包吃了）。
例14： 我们去公园玩，先散了步，看了花，然后在长椅上坐着……（听了一首中文歌✅）/（把那首中文歌听了）。
例15： 他走进办公室，先开了空调，然后坐下来……（写了一份总结✅）/（把那份总结写了）。
例16： 去商场购物时，我先买了一件衬衫，后来又去五楼……（买了一双凉鞋✅）/（把那双凉鞋买了）。
例17： 大家聚餐时，先喝了果汁，又聊了天，最后一起……（喝了一瓶红酒✅）/（把那瓶红酒喝了）。
例18： 在火车站候车时，我先查了时刻表，然后去书报亭……（买了一张地图✅）/（把那张地图买了）。
例19： 回到家后，他先放下书包，脱了外套，然后去厨房……（煮了一碗面条✅）/（把那碗面条煮了）。
例20： 准备开会前，我先打印了材料，然后去休息间……（泡了一壶热茶✅）/（把那壶热茶泡了）。
例21： 回到家后，我先洗了手，然后去厨房……（切了一个西瓜✅）/（把那个西瓜切了）。
例22： 昨天去参观博物馆，我们先听了导游的讲解，最后在门口的纪念品店……（买了一张明信片✅）/（把那张明信片买了）。
例23： 昨天我去医院看病，医生先问了情况，然后给我……（开了一些药✅）/（把那些药开了）。
例24： 他今天起得很早，洗漱完以后走到阳台，看着外面的风景安静地……（喝了一杯温水✅）/（把那杯温水喝了）。
例25： 到了火车站，我们先取了票，然后去候车室……（找到了一个座位✅）/（把那个座位找到了）。
例26： 会议开始前，秘书先给大家发了材料，然后走到台前……（打开了投影仪✅）/（把那台投影仪打开了）。
例27： 上车以后，他先系好了安全带，然后慢慢地……（发动了汽车✅）/（把汽车发动了）。
例28： 经理上午到了公司，先给自己倒了水，然后坐下来打开电脑……（看了一份文件✅）/（把那份文件看了）。
例29： 下午的汉语课结束以后，我去了一趟图书馆，在三楼……（借了两本小说✅）/（把那两本小说借了）。
例30： 下了飞机，我们先取了行李，然后在停车场……（开走了我的车✅）/（把我的车开走了）。
例31： 进门后，他先脱了鞋，然后把包放下，又给自己……（接好了一杯热水✅）/（把那杯热水接好了）。
例32： 我们先去了博物馆，然后去了公园，最后在街角……（喝了一杯奶茶✅）/（把那杯奶茶喝了）。
例33： 老师走进教室，把书本放在讲台上，然后转身在黑板上……（写了一个生词✅）/（把那个生词写了）。
例34： 晚饭做好了，大家先去洗了手，然后在客厅里一边聊天一边……（吃水果✅）/（把水果吃了）。
例35： 他打开电脑，输入了密码，然后点开浏览器……（看了一条新闻✅）/（把那条新闻看了）。
例36： 周末我们在家里大扫除，先擦了窗户，洗了衣服，然后下楼……（扔了两袋垃圾✅）/（把那两袋垃圾扔了）。
例37： 昨天我去菜市场，买了青菜，买了豆腐，最后为了招待客人还……（买了一条鱼✅）/（把那条鱼买了）。
例38： 到了银行，他先拿了号，然后在休息区的沙发上……（看了一本杂志✅）/（把那本杂志看了）。
例39： 昨天面试的时候，他先介绍了自己，然后回答了问题，最后给面试官……（留下了一份简历✅）/（把那份简历留下了）。
例40： 妈妈回到家，先换了衣服，然后去厨房系上围裙，开始……（做晚餐✅）/（把晚餐做了）。
例41： 到了酒店，我们先在前台拿了房卡，坐电梯上楼放好行李，接着就……（喝了一瓶矿泉水✅）/（把那瓶矿泉水喝了）。
例42： 陪奶奶去医院看病，我们先排队挂号，看完医生后去一楼……（买了几盒感冒药✅）/（把那几盒感冒药买了）。
例43： 打开包裹后，她先看了看说明书，然后小心地从盒子里……（拿出来了一个新手机✅）/（把那个新手机拿出来了）。
例44： 我们先去前台办了入住，然后拿着房卡，上楼去……（找到了我们的房间✅）/（把我们的房间找到了）。
例45： 过了机场安检，距离起飞还有很长时间，我就去旁边的书店……（买了一本杂志✅）/（把那本杂志买了）。
例46： 下午我们去公园散步，在湖边坐了一会儿，然后拿出面包……（喂了几只天鹅✅）/（把那几只天鹅喂了）
例47： 电影开场前，我们先买了爆米花，然后向工作人员……（买了两张票✅）/（把那两张票买了）。
例48： 搬家那天特别累，把东西都搬进新家后，大家去楼下的餐厅……（吃了顿火锅✅）/（把那顿火锅吃了）。
例49： 她拆开信封，拿出信纸，坐在桌子前认真地……（读了一遍这封信✅）/（把这封信读了一遍）。
例50： 晚上加完班回到家，他先洗了一个热水澡，然后躺在沙发上……（听了一遍那首老歌✅）/（把那首老歌听了一遍）。
"""

def clean_option(text: str) -> str:
    """清理候选项：删除 ✅、多余空格、句末标点。"""
    text = text.replace("✅", "").strip()
    text = re.sub(r"\s+", "", text)
    text = text.strip("。.!！?？")
    return text


def split_options(options_part: str) -> List[str]:
    """
    兼容以下形式：
    （A✅）/（B）
    （A✅）（B）
    (A ✅ / B)
    """
    s = options_part.strip()
    s = s.replace("（", "(").replace("）", ")")
    chunks = re.findall(r"\(([^()]*)\)", s)

    pieces = []
    if chunks:
        for ch in chunks:
            subparts = re.split(r"\s*/\s*", ch)
            pieces.extend([p.strip() for p in subparts if p.strip()])
    else:
        s = re.sub(r"[()]", "", s)
        pieces = [p.strip() for p in re.split(r"\s*/\s*", s) if p.strip()]

    return pieces


def parse_data(raw_str: str, is_ba_dataset: bool) -> List[Dict]:
    """
    is_ba_dataset=True:
        ✅ 项是 ba_sent，另一项是 svo_sent
    is_ba_dataset=False:
        ✅ 项是 svo_sent，另一项是 ba_sent
    """
    data = []
    current_type = ""
    example_id = 0

    for raw_line in raw_str.strip().split("\n"):
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("(情况") or line.startswith("（情况"):
            if is_ba_dataset:
                current_type = "物理状态改变" if "1" in line else "空间位移"
            else:
                current_type = "习惯性动作与泛指" if "1" in line else "叙述经历和日程"
            continue

        if "……" not in line:
            continue

        context_part, options_part = line.split("……", 1)

        m = re.match(r"^例\s*(\d+)\s*[:：]\s*(.*)$", context_part.strip())
        if m:
            local_id = int(m.group(1))
            context = m.group(2).strip()
        else:
            example_id += 1
            local_id = example_id
            context = context_part.strip()

        pieces = split_options(options_part)

        preferred = None
        nonpreferred = None
        for p in pieces:
            if "✅" in p:
                preferred = clean_option(p)
            else:
                # 只取第一个非 ✅ 项
                if nonpreferred is None:
                    nonpreferred = clean_option(p)

        if preferred is None or nonpreferred is None:
            print("[解析警告] 未能解析：", line)
            continue

        if is_ba_dataset:
            ba_sent = preferred
            svo_sent = nonpreferred
            gold = "ba"
            dataset = "ba_preferred"
        else:
            svo_sent = preferred
            ba_sent = nonpreferred
            gold = "svo"
            dataset = "svo_preferred"

        data.append({
            "dataset": dataset,
            "type": current_type,
            "example_id": local_id,
            "context": context,
            "ba_sent": ba_sent,
            "svo_sent": svo_sent,
            "gold": gold
        })

    return data


data_ba = parse_data(raw_data_ba, is_ba_dataset=True)
data_svo = parse_data(raw_data_svo, is_ba_dataset=False)

if DEBUG_SMALL:
    data_ba = data_ba[:DEBUG_N]
    data_svo = data_svo[:DEBUG_N]

print(f"成功加载数据：BA偏好组 {len(data_ba)} 条, SVO偏好组 {len(data_svo)} 条")
print("示例 BA:", data_ba[0])
print("示例 SVO:", data_svo[0])


# ============================================================
# 2. 可选 MacBERT 基线
# ============================================================

def run_macbert_baseline(data_ba: List[Dict], data_svo: List[Dict]) -> None:
    """
    MacBERT CSC baseline:
    - BA偏好组：检查非优选 SVO 是否被纠错模型检出
    - SVO偏好组：检查非优选 BA 是否被纠错模型检出
    """
    try:
        try:
            from pycorrector import MacBertCorrector
        except Exception:
            from pycorrector.macbert.macbert_corrector import MacBertCorrector
    except Exception as e:
        print("无法导入 MacBertCorrector，跳过 MacBERT baseline。错误：", repr(e))
        for d in data_ba:
            d["macbert_miss_svo"] = "未运行"
        for d in data_svo:
            d["macbert_miss_ba"] = "未运行"
        return

    print("\n[加载 MacBERT CSC 模型...]")
    macbert = MacBertCorrector("shibing624/macbert4csc-base-chinese")

    def get_errors(result):
        if isinstance(result, dict):
            return result.get("errors", [])
        if isinstance(result, tuple) and len(result) > 1:
            return result[1]
        return []

    for d in tqdm(data_ba, desc="MacBERT on BA-preferred group"):
        text = d["context"] + d["svo_sent"]
        result = macbert.correct(text)
        errors = get_errors(result)
        d["macbert_miss_svo"] = "漏检_认为SVO正确" if len(errors) == 0 else "检出错误"

    for d in tqdm(data_svo, desc="MacBERT on SVO-preferred group"):
        text = d["context"] + d["ba_sent"]
        result = macbert.correct(text)
        errors = get_errors(result)
        d["macbert_miss_ba"] = "漏检_认为把字句正确" if len(errors) == 0 else "检出错误"

    del macbert
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


if RUN_MACBERT:
    run_macbert_baseline(data_ba, data_svo)
else:
    for d in data_ba:
        d["macbert_miss_svo"] = "未运行"
    for d in data_svo:
        d["macbert_miss_ba"] = "未运行"


df_ba_base = pd.DataFrame(data_ba)
df_svo_base = pd.DataFrame(data_svo)


# ============================================================
# 3. 模型列表
# ============================================================

MODEL_SPECS = [
    # 只保留 1-2 个模型测试。跑通后再逐步增加。


    # DeepSeek-R1 原版不要在 Colab 跑；下面是可跑的蒸馏版
    # {"alias": "DeepSeek-R1-Distill-Qwen-7B", "model_id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B", "quant": DEFAULT_QUANT, "batch_size": 4},
    # {"alias": "DeepSeek-R1-Distill-Qwen-14B", "model_id": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", "quant": DEFAULT_QUANT, "batch_size": 2},


   # Qwen2.5 Base✅
    #{"alias": "Qwen2.5-0.5B-Base", "model_id": "Qwen/Qwen2.5-0.5B", "quant": "4bit", "batch_size": 16},
    #{"alias": "Qwen2.5-1.5B-Base", "model_id": "Qwen/Qwen2.5-1.5B", "quant": "4bit", "batch_size": 8},
    #{"alias": "Qwen2.5-3B-Base", "model_id": "Qwen/Qwen2.5-3B", "quant": "4bit", "batch_size": 8},
    #{"alias": "Qwen2.5-7B-Base", "model_id": "Qwen/Qwen2.5-7B", "quant": "4bit", "batch_size": 4},
    #{"alias": "Qwen2.5-14B-Base", "model_id": "Qwen/Qwen2.5-14B", "quant": "4bit", "batch_size": 1},

   # Qwen3 Base✅
    #{"alias": "Qwen3-0.6B-Base", "model_id": "Qwen/Qwen3-0.6B-Base", "quant": "4bit", "batch_size": 16},
    #{"alias": "Qwen3-1.7B-Base", "model_id": "Qwen/Qwen3-1.7B-Base", "quant": "4bit", "batch_size": 8},
    #{"alias": "Qwen3-4B-Base", "model_id": "Qwen/Qwen3-4B-Base", "quant": "4bit", "batch_size": 8},
    #{"alias": "Qwen3-8B-Base", "model_id": "Qwen/Qwen3-8B-Base", "quant": "4bit", "batch_size": 4},
    #{"alias": "Qwen3-14B-Base", "model_id": "Qwen/Qwen3-14B-Base", "quant": "4bit", "batch_size": 1},


   # Yi
    #{"alias": "Yi-1.5-6B-Base", "model_id": "01-ai/Yi-1.5-6B", "quant": "4bit", "batch_size": 4},
    #{"alias": "Yi-1.5-9B-Base", "model_id": "01-ai/Yi-1.5-9B", "quant": "4bit", "batch_size": 2},

   # GLM
   #{"alias": "GLM-4-9B-Base", "model_id": "zai-org/glm-4-9b-hf", "quant": "4bit", "batch_size": 2},

   # Internlm
   #{"alias": "InternLM2.5-7B-Base", "model_id": "internlm/internlm2_5-7b", "quant": "4bit", "batch_size": 4},

   # no-Chinese
   # {"alias": "Pythia-410M-Base", "model_id": "EleutherAI/pythia-410m", "quant": "4bit", "batch_size": 16},
   # {"alias": "Pythia-1.4B-Base", "model_id": "EleutherAI/pythia-1.4b", "quant": "4bit", "batch_size": 8},
    #{"alias": "Pythia-2.8B-Base", "model_id": "EleutherAI/pythia-2.8b", "quant": "4bit", "batch_size": 8},
    #{"alias": "Mistral-7B-v0.3-Base", "model_id": "mistralai/Mistral-7B-v0.3", "quant": "4bit", "batch_size": 4},

   #{"alias": "Llama-3-8B-Base", "model_id": "meta-llama/Meta-Llama-3-8B", "quant": "4bit", "batch_size": 4},
    #{"alias": "Llama-2-7B-Base", "model_id": "meta-llama/Llama-2-7b-hf", "quant": "4bit", "batch_size": 4},
    #{"alias": "Llama-3.1-8B-Instruct", "model_id": "meta-llama/Llama-3.1-8B-Instruct", "quant": "4bit", "batch_size": 4},


]

# 快速测试时只跑第一个模型：
# MODEL_SPECS = MODEL_SPECS[:1]


# ============================================================
# 4. 模型加载与 surprisal 计算
# ============================================================

def cuda_empty_cache():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def get_compute_dtype():
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
        return torch.bfloat16
    return torch.float16


def load_tokenizer_and_model(model_id: str, quant: str = "4bit"):
    compute_dtype = get_compute_dtype()

    print(f"\n[加载 tokenizer] {model_id}")
    tokenizer = AutoTokenizer.from_pretrained(
        model_id,
        trust_remote_code=True
    )

    if tokenizer.pad_token_id is None:
        if tokenizer.eos_token_id is not None:
            tokenizer.pad_token = tokenizer.eos_token
        elif tokenizer.bos_token_id is not None:
            tokenizer.pad_token = tokenizer.bos_token

    print(f"[加载 model] {model_id} | quant={quant}")

    load_kwargs = dict(
        trust_remote_code=True,
        device_map="auto",
        low_cpu_mem_usage=True
    )

    if quant == "4bit":
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=compute_dtype
        )
        load_kwargs["quantization_config"] = bnb_config
        load_kwargs["torch_dtype"] = compute_dtype

    elif quant == "8bit":
        bnb_config = BitsAndBytesConfig(load_in_8bit=True)
        load_kwargs["quantization_config"] = bnb_config
        load_kwargs["torch_dtype"] = compute_dtype

    elif quant == "none":
        load_kwargs["torch_dtype"] = compute_dtype

    else:
        raise ValueError(f"Unknown quant mode: {quant}")

    model = AutoModelForCausalLM.from_pretrained(model_id, **load_kwargs)
    model.eval()

    # scoring 不需要 KV cache，关闭可省显存
    if hasattr(model, "config"):
        model.config.use_cache = False

    return tokenizer, model


def get_model_input_device(model):
    try:
        return model.get_input_embeddings().weight.device
    except Exception:
        return next(model.parameters()).device


@dataclass
class ScoreItem:
    prefix: str
    continuation: str
    row_idx: int
    key: str


def encode_for_conditional_scoring(tokenizer, prefix: str, continuation: str):
    """
    计算 P(continuation | prefix)。

    使用 prefix_ids + continuation_ids 的显式拼接，避免 tokenizer 在边界处发生
    BPE/SentencePiece 合并导致 continuation 起点错位。

    若 prefix 为空且 tokenizer 有 bos_token_id，则用 BOS 作为空语境起点；
    若没有 BOS，则第一个 continuation token 无法被条件化评分，只从第二个 token 开始算。
    """
    prefix_ids = tokenizer.encode(prefix, add_special_tokens=False)
    cont_ids = tokenizer.encode(continuation, add_special_tokens=False)

    if len(cont_ids) == 0:
        return [], [], 0

    if len(prefix_ids) == 0 and tokenizer.bos_token_id is not None:
        input_ids = [tokenizer.bos_token_id] + cont_ids
        score_start = 1
    else:
        input_ids = prefix_ids + cont_ids
        if len(prefix_ids) > 0:
            score_start = len(prefix_ids)
        else:
            # 没有 prefix 且没有 BOS：第一个 token 没有前文，跳过
            score_start = 1

    labels = [-100] * len(input_ids)
    if score_start < len(input_ids):
        labels[score_start:] = input_ids[score_start:]

    return input_ids, labels, len(cont_ids)


@torch.inference_mode()
def _score_batch_core(model, tokenizer, batch_items: List[ScoreItem]) -> List[Dict]:
    device = get_model_input_device(model)

    encoded = []
    for item in batch_items:
        input_ids, labels, cont_token_count = encode_for_conditional_scoring(
            tokenizer,
            item.prefix,
            item.continuation
        )
        encoded.append((input_ids, labels, cont_token_count, item))

    max_len = max(len(x[0]) for x in encoded)
    pad_id = tokenizer.pad_token_id
    if pad_id is None:
        pad_id = tokenizer.eos_token_id if tokenizer.eos_token_id is not None else 0

    input_tensor = torch.full((len(encoded), max_len), pad_id, dtype=torch.long)
    label_tensor = torch.full((len(encoded), max_len), -100, dtype=torch.long)
    attention_mask = torch.zeros((len(encoded), max_len), dtype=torch.long)

    for i, (ids, labels, _, _) in enumerate(encoded):
        L = len(ids)
        input_tensor[i, :L] = torch.tensor(ids, dtype=torch.long)
        label_tensor[i, :L] = torch.tensor(labels, dtype=torch.long)
        attention_mask[i, :L] = 1

    input_tensor = input_tensor.to(device)
    label_tensor = label_tensor.to(device)
    attention_mask = attention_mask.to(device)

    outputs = model(
        input_ids=input_tensor,
        attention_mask=attention_mask,
        use_cache=False
    )
    logits = outputs.logits

    # Causal LM: logits[:, t] 预测 input_ids[:, t+1]
    shift_logits = logits[:, :-1, :].contiguous()
    shift_labels = label_tensor[:, 1:].contiguous()

    vocab_size = shift_logits.size(-1)
    losses = F.cross_entropy(
        shift_logits.float().view(-1, vocab_size),
        shift_labels.view(-1),
        reduction="none",
        ignore_index=-100
    ).view(shift_labels.shape)

    mask = shift_labels.ne(-100)

    results = []
    for i, (_, _, cont_token_count, item) in enumerate(encoded):
        valid_losses = losses[i][mask[i]]

        if valid_losses.numel() == 0:
            total_surp = float("nan")
            mean_surp = float("nan")
            first_token_surp = float("nan")
            bits_per_token = float("nan")
            scored_tokens = 0
        else:
            total_surp = valid_losses.sum().item()
            mean_surp = valid_losses.mean().item()
            first_token_surp = valid_losses[0].item()
            bits_per_token = mean_surp / math.log(2)
            scored_tokens = int(valid_losses.numel())

        results.append({
            "row_idx": item.row_idx,
            "key": item.key,
            "sum_surp": total_surp,
            "mean_surp": mean_surp,
            "first_token_surp": first_token_surp,
            "bits_per_token": bits_per_token,
            "continuation_token_count": cont_token_count,
            "scored_token_count": scored_tokens
        })

    del outputs, logits, shift_logits, shift_labels, losses
    return results


def score_items(model, tokenizer, items: List[ScoreItem], batch_size: int = 4) -> List[Dict]:
    """
    带 OOM 自动降 batch 的 scoring。
    """
    all_results = []
    i = 0

    pbar = tqdm(total=len(items), desc="Scoring", leave=False)

    while i < len(items):
        cur_bs = min(batch_size, len(items) - i)

        while True:
            batch_items = items[i:i + cur_bs]
            try:
                batch_results = _score_batch_core(model, tokenizer, batch_items)
                all_results.extend(batch_results)
                i += cur_bs
                pbar.update(cur_bs)
                break

            except RuntimeError as e:
                msg = str(e).lower()
                if "out of memory" in msg or "cuda" in msg and "memory" in msg:
                    cuda_empty_cache()
                    if cur_bs == 1:
                        pbar.close()
                        raise RuntimeError("batch_size=1 仍然 OOM，请换更小模型或更大 GPU。") from e
                    cur_bs = max(1, cur_bs // 2)
                    print(f"[OOM] 自动降低 batch_size 到 {cur_bs}")
                else:
                    pbar.close()
                    raise e

    pbar.close()
    return all_results


# ============================================================
# 5. 单模型评测逻辑
# ============================================================

def build_score_items_for_df(df: pd.DataFrame) -> List[ScoreItem]:
    items = []
    for idx, row in df.iterrows():
        prefix = row["context"]

        items.extend([
            ScoreItem(prefix=prefix, continuation=row["ba_sent"], row_idx=idx, key="ctx_ba"),
            ScoreItem(prefix=prefix, continuation=row["svo_sent"], row_idx=idx, key="ctx_svo"),
            ScoreItem(prefix="", continuation=row["ba_sent"], row_idx=idx, key="noctx_ba"),
            ScoreItem(prefix="", continuation=row["svo_sent"], row_idx=idx, key="noctx_svo"),
        ])
    return items


def attach_scores(df: pd.DataFrame, score_results: List[Dict]) -> pd.DataFrame:
    df = df.copy()

    for r in score_results:
        idx = r["row_idx"]
        key = r["key"]

        df.loc[idx, f"{key}_sum_surp"] = r["sum_surp"]
        df.loc[idx, f"{key}_mean_surp"] = r["mean_surp"]
        df.loc[idx, f"{key}_first_token_surp"] = r["first_token_surp"]
        df.loc[idx, f"{key}_bits_per_token"] = r["bits_per_token"]
        df.loc[idx, f"{key}_cont_token_count"] = r["continuation_token_count"]
        df.loc[idx, f"{key}_scored_token_count"] = r["scored_token_count"]

    return df


def add_preference_columns(df: pd.DataFrame, preferred: str, metric: str = "mean") -> pd.DataFrame:
    """
    preferred:
        "ba"  for BA偏好组
        "svo" for SVO偏好组
    metric:
        "mean" or "sum"
    """
    df = df.copy()

    ba_col = f"ctx_ba_{metric}_surp"
    svo_col = f"ctx_svo_{metric}_surp"

    noctx_ba_col = f"noctx_ba_{metric}_surp"
    noctx_svo_col = f"noctx_svo_{metric}_surp"

    if preferred == "ba":
        df[f"ctx_prefer_{metric}"] = df.apply(
            lambda r: "正确_把字句" if r[ba_col] < r[svo_col] else "错误_SVO",
            axis=1
        )
        df["ctx_prefer_first_token"] = df.apply(
            lambda r: "正确_把字句" if r["ctx_ba_first_token_surp"] < r["ctx_svo_first_token_surp"] else "错误_SVO",
            axis=1
        )
        df[f"noctx_prefer_{metric}"] = df.apply(
            lambda r: "把字句" if r[noctx_ba_col] < r[noctx_svo_col] else "SVO",
            axis=1
        )
        df[f"context_helped_{metric}"] = df.apply(
            lambda r: "是" if r[ba_col] < r[noctx_ba_col] else "否",
            axis=1
        )

    elif preferred == "svo":
        df[f"ctx_prefer_{metric}"] = df.apply(
            lambda r: "正确_SVO" if r[svo_col] < r[ba_col] else "错误_把字句",
            axis=1
        )
        df["ctx_prefer_first_token"] = df.apply(
            lambda r: "正确_SVO" if r["ctx_svo_first_token_surp"] < r["ctx_ba_first_token_surp"] else "错误_把字句",
            axis=1
        )
        df[f"noctx_prefer_{metric}"] = df.apply(
            lambda r: "SVO" if r[noctx_svo_col] < r[noctx_ba_col] else "把字句",
            axis=1
        )
        df[f"context_helped_{metric}"] = df.apply(
            lambda r: "是" if r[svo_col] < r[noctx_svo_col] else "否",
            axis=1
        )

    else:
        raise ValueError("preferred must be 'ba' or 'svo'")

    return df


def summarize_result(df_ba: pd.DataFrame, df_svo: pd.DataFrame, model_alias: str, metric: str = "mean") -> Dict:
    ba_ctx_acc = (df_ba[f"ctx_prefer_{metric}"] == "正确_把字句").mean()
    ba_first_acc = (df_ba["ctx_prefer_first_token"] == "正确_把字句").mean()
    ba_noctx_rate = (df_ba[f"noctx_prefer_{metric}"] == "把字句").mean()
    ba_context_help = (df_ba[f"context_helped_{metric}"] == "是").mean()

    svo_ctx_acc = (df_svo[f"ctx_prefer_{metric}"] == "正确_SVO").mean()
    svo_first_acc = (df_svo["ctx_prefer_first_token"] == "正确_SVO").mean()
    svo_noctx_rate = (df_svo[f"noctx_prefer_{metric}"] == "SVO").mean()
    svo_context_help = (df_svo[f"context_helped_{metric}"] == "是").mean()

    summary = {
        "model": model_alias,
        "decision_metric": metric,

        "ba_group_ctx_sentence_acc": ba_ctx_acc,
        "ba_group_ctx_first_token_acc": ba_first_acc,
        "ba_group_noctx_ba_rate": ba_noctx_rate,
        "ba_group_context_help_rate": ba_context_help,

        "svo_group_ctx_sentence_acc": svo_ctx_acc,
        "svo_group_ctx_first_token_acc": svo_first_acc,
        "svo_group_noctx_svo_rate": svo_noctx_rate,
        "svo_group_context_help_rate": svo_context_help,

        "macro_ctx_sentence_acc": (ba_ctx_acc + svo_ctx_acc) / 2,
        "macro_ctx_first_token_acc": (ba_first_acc + svo_first_acc) / 2,
    }

    if "macbert_miss_svo" in df_ba.columns:
        summary["macbert_svo_miss_rate_in_ba_group"] = (df_ba["macbert_miss_svo"] == "漏检_认为SVO正确").mean()

    if "macbert_miss_ba" in df_svo.columns:
        summary["macbert_ba_miss_rate_in_svo_group"] = (df_svo["macbert_miss_ba"] == "漏检_认为把字句正确").mean()

    return summary


def safe_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", name)


def run_one_model(spec: Dict) -> Dict:
    alias = spec["alias"]
    model_id = spec["model_id"]
    quant = spec.get("quant", DEFAULT_QUANT)
    batch_size = spec.get("batch_size", 4)

    print(f"\n{'=' * 80}")
    print(f"[开始评测] {alias} | {model_id} | quant={quant} | batch_size={batch_size}")
    print(f"{'=' * 80}")

    tokenizer, model = load_tokenizer_and_model(model_id, quant=quant)

    try:
        # BA preferred group
        print(f"\n[{alias}] BA偏好组 scoring...")
        df_ba = df_ba_base.copy()
        ba_items = build_score_items_for_df(df_ba)
        ba_scores = score_items(model, tokenizer, ba_items, batch_size=batch_size)
        df_ba = attach_scores(df_ba, ba_scores)
        df_ba = add_preference_columns(df_ba, preferred="ba", metric=DECISION_METRIC)
        df_ba["model"] = alias
        df_ba["model_id"] = model_id

        # SVO preferred group
        print(f"\n[{alias}] SVO偏好组 scoring...")
        df_svo = df_svo_base.copy()
        svo_items = build_score_items_for_df(df_svo)
        svo_scores = score_items(model, tokenizer, svo_items, batch_size=batch_size)
        df_svo = attach_scores(df_svo, svo_scores)
        df_svo = add_preference_columns(df_svo, preferred="svo", metric=DECISION_METRIC)
        df_svo["model"] = alias
        df_svo["model_id"] = model_id

        # summary
        summary = summarize_result(df_ba, df_svo, model_alias=alias, metric=DECISION_METRIC)
        print_summary(summary)

        # save
        name = safe_name(alias)
        ba_path = os.path.join(OUTPUT_DIR, f"{name}_ba_preferred_results.csv")
        svo_path = os.path.join(OUTPUT_DIR, f"{name}_svo_preferred_results.csv")

        df_ba.to_csv(ba_path, index=False, encoding="utf-8-sig")
        df_svo.to_csv(svo_path, index=False, encoding="utf-8-sig")

        print(f"[保存] {ba_path}")
        print(f"[保存] {svo_path}")

        summary["ba_csv"] = ba_path
        summary["svo_csv"] = svo_path
        return summary

    finally:
        print(f"\n[清理显存] {alias}")
        del model
        del tokenizer
        cuda_empty_cache()


def print_summary(s: Dict):
    print("\n================== 实验结果摘要 ==================")
    print(f"模型: {s['model']}")
    print(f"决策指标: {s['decision_metric']}_surprisal，越低越偏好")
    print("")
    print(f"BA偏好组：")
    print(f"  有语境 sentence-level 正确偏好把字句: {s['ba_group_ctx_sentence_acc']:.2%}")
    print(f"  有语境 first-token 正确偏好把字句:     {s['ba_group_ctx_first_token_acc']:.2%}")
    print(f"  无语境偏好把字句比例:                  {s['ba_group_noctx_ba_rate']:.2%}")
    print(f"  语境降低把字句 surprisal 比例:          {s['ba_group_context_help_rate']:.2%}")
    print("")
    print(f"SVO偏好组：")
    print(f"  有语境 sentence-level 正确偏好SVO:      {s['svo_group_ctx_sentence_acc']:.2%}")
    print(f"  有语境 first-token 正确偏好SVO:         {s['svo_group_ctx_first_token_acc']:.2%}")
    print(f"  无语境偏好SVO比例:                      {s['svo_group_noctx_svo_rate']:.2%}")
    print(f"  语境降低SVO surprisal 比例:             {s['svo_group_context_help_rate']:.2%}")
    print("")
    print(f"宏平均 sentence-level accuracy:           {s['macro_ctx_sentence_acc']:.2%}")
    print(f"宏平均 first-token accuracy:              {s['macro_ctx_first_token_acc']:.2%}")
    print("===================================================")


# ============================================================
# 6. 运行全部模型
# ============================================================

all_summaries = []

for spec in MODEL_SPECS:
    try:
        summary = run_one_model(spec)
        all_summaries.append(summary)

        summary_path = os.path.join(OUTPUT_DIR, "summary_so_far.csv")
        pd.DataFrame(all_summaries).to_csv(summary_path, index=False, encoding="utf-8-sig")
        print(f"[保存 summary] {summary_path}")

    except Exception as e:
        print(f"\n[错误] 模型 {spec['alias']} 运行失败：{repr(e)}")
        all_summaries.append({
            "model": spec["alias"],
            "model_id": spec["model_id"],
            "error": repr(e)
        })
        cuda_empty_cache()


summary_df = pd.DataFrame(all_summaries)
summary_path = os.path.join(OUTPUT_DIR, "all_model_summary.csv")
summary_df.to_csv(summary_path, index=False, encoding="utf-8-sig")
print(f"\n[最终 summary 保存] {summary_path}")

# 打包下载
zip_base = "./surprisal_results"
zip_path = shutil.make_archive(zip_base, "zip", OUTPUT_DIR)
print(f"[ZIP] {zip_path}")

try:
    from google.colab import files
    files.download(zip_path)
except Exception as e:
    print("自动下载失败，可手动在左侧文件栏下载：", zip_path)



from huggingface_hub import whoami

print(whoami())

from huggingface_hub import model_info

model_info("meta-llama/Llama-3.1-8B", token=True)
print("Llama access OK")