# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15n5wgp8G8cQ3uVt5e7anzytyQqLuqayx
"""

# -*- coding: utf-8 -*-
"""
Colab script: Re-test MacBERT / macbert4csc on all contextual BA/SVO test sentences.

What this script reports:
1. Sentence-level binary error-detection accuracy over all 400 contextualized target sentences.
   - Gold error = preference_in_source_context == 'non-preferred'
   - MacBERT predicts error = it returns at least one edit/error
2. Miss rate on the 200 pragmatically infelicitous continuations.
   - Miss = gold error sentence receives no edit/error from MacBERT
3. Pair-level pragmatic correction accuracy over 200 contextual minimal pairs.
   - Correct pair = preferred sentence accepted AND non-preferred sentence flagged

Expected use in Colab:
- Upload these two files to /content, or put them in Google Drive and edit BA_CSV/SVO_CSV below:
  ba_svo_llm_surprisal_800_tests_Ba_context.csv
  ba_svo_llm_surprisal_800_tests_SVO_context.csv
"""

import os
import sys
import json
import zipfile
import subprocess
from pathlib import Path
from typing import Any, Dict, List

# ============================================================
# 0. Install dependencies in Colab
# ============================================================

def pip_install(packages: List[str]) -> None:
    cmd = [sys.executable, "-m", "pip", "install", "-q", "-U"] + packages
    print("[pip]", " ".join(cmd))
    subprocess.check_call(cmd)

# In Colab, torch is usually preinstalled. These are enough for pycorrector + MacBERT.
pip_install([
    "pycorrector",
    "transformers",
    "sentencepiece",
    "pandas",
    "tqdm",
    "openpyxl",
])

import pandas as pd
from tqdm.auto import tqdm

os.environ["TOKENIZERS_PARALLELISM"] = "false"

# ============================================================
# 1. Paths
# ============================================================

BA_CSV = "/content/ba_svo_llm_surprisal_800_tests_Ba_context.csv"
SVO_CSV = "/content/ba_svo_llm_surprisal_800_tests_SVO_context.csv"  # filename uses SOV, content is SVO-preferred
OUTPUT_DIR = "/content/macbert_baseline_results"
MODEL_NAME = "shibing624/macbert4csc-base-chinese"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# If files are not found, ask the user to upload them in Colab.
if not (os.path.exists(BA_CSV) and os.path.exists(SVO_CSV)):
    print("CSV files not found at the default paths.")
    print("Please upload the two CSV files now:")
    print("  1) ba_svo_llm_surprisal_800_tests_Ba_context.csv")
    print("  2) ba_svo_llm_surprisal_800_tests_SVO_context.csv")
    try:
        from google.colab import files
        uploaded = files.upload()
        print("Uploaded files:", list(uploaded.keys()))
    except Exception as e:
        raise FileNotFoundError(
            "CSV files were not found and automatic Colab upload is unavailable. "
            "Please edit BA_CSV and SVO_CSV to the correct file paths."
        ) from e

# Try to locate the files again after upload.
if not os.path.exists(BA_CSV):
    candidates = list(Path("/content").glob("*BA_context*.csv"))
    if candidates:
        BA_CSV = str(candidates[0])
if not os.path.exists(SVO_CSV):
    candidates = list(Path("/content").glob("*SOV_context*.csv")) + list(Path("/content").glob("*SVO_context*.csv"))
    if candidates:
        SVO_CSV = str(candidates[0])

print("[BA_CSV]", BA_CSV)
print("[SVO_CSV]", SVO_CSV)

# ============================================================
# 2. Load data
# ============================================================

def load_contextual_csv(path: str, expected_context_preference: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {
        "global_test_id",
        "source_context_preference",
        "pair_id",
        "construction_candidate",
        "preference_in_source_context",
        "full_test_sentence",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"{path} is missing required columns: {missing}")

    # Keep only contextual rows if such a column exists.
    if "context_status" in df.columns:
        df = df[df["context_status"].astype(str).str.contains("有语境", na=False)].copy()

    # Safety check: the BA file should be BA-preferred, the SOV/SVO file should be SVO-preferred.
    observed = set(df["source_context_preference"].dropna().astype(str).unique())
    if expected_context_preference not in observed:
        print(f"[Warning] Expected {expected_context_preference} in {path}, observed: {observed}")

    return df

ba_df = load_contextual_csv(BA_CSV, "BA-preferred")
svo_df = load_contextual_csv(SVO_CSV, "SVO-preferred")

all_df = pd.concat([ba_df, svo_df], ignore_index=True)
all_df["gold_is_error"] = all_df["preference_in_source_context"].astype(str).eq("non-preferred")
all_df["gold_label"] = all_df["gold_is_error"].map({True: "infelicitous", False: "felicitous"})
all_df["sentence_for_macbert"] = all_df["full_test_sentence"].astype(str)

print("\nLoaded data")
print("BA-preferred rows:", len(ba_df))
print("SVO-preferred rows:", len(svo_df))
print("All contextual target sentences:", len(all_df))
print("Gold infelicitous continuations:", int(all_df["gold_is_error"].sum()))
print("Gold felicitous continuations:", int((~all_df["gold_is_error"]).sum()))

# ============================================================
# 3. Load MacBERT corrector
# ============================================================

try:
    from pycorrector import MacBertCorrector
except Exception:
    from pycorrector.macbert.macbert_corrector import MacBertCorrector

print(f"\nLoading MacBERT corrector: {MODEL_NAME}")
try:
    corrector = MacBertCorrector(MODEL_NAME)
except TypeError:
    # Some older pycorrector versions use a no-argument initializer.
    print("MacBertCorrector(model_name) failed; trying MacBertCorrector() ...")
    corrector = MacBertCorrector()

# ============================================================
# 4. Robust wrapper for pycorrector outputs
# ============================================================

def normalize_corrector_result(source_text: str, result: Any) -> Dict[str, Any]:
    """Normalize possible pycorrector output formats to a dict."""
    corrected = None
    errors = []

    if isinstance(result, dict):
        corrected = (
            result.get("target")
            or result.get("corrected_text")
            or result.get("correct_text")
            or result.get("corrected_sent")
            or result.get("source")
            or source_text
        )
        errors = result.get("errors", result.get("details", [])) or []

    elif isinstance(result, tuple):
        # Common old format: (corrected_text, errors)
        if len(result) >= 1:
            corrected = result[0]
        if len(result) >= 2:
            errors = result[1] or []

    elif isinstance(result, list):
        # Rare case: list of errors or [corrected, errors]
        if len(result) == 2 and isinstance(result[0], str):
            corrected = result[0]
            errors = result[1] or []
        else:
            corrected = source_text
            errors = result

    else:
        corrected = str(result) if result is not None else source_text
        errors = []

    if corrected is None:
        corrected = source_text

    # If pycorrector does not return errors but returns a changed text, count character differences as edits.
    # This is a fallback; normally MacBertCorrector returns an explicit errors list.
    if not errors and corrected != source_text:
        errors = [(src, tgt, i) for i, (src, tgt) in enumerate(zip(source_text, corrected)) if src != tgt]
        if len(corrected) != len(source_text):
            errors.append(("<length_change>", len(source_text), len(corrected)))

    return {
        "source": source_text,
        "corrected": corrected,
        "errors": errors,
        "num_errors": len(errors),
        "accepted_no_edit": len(errors) == 0,
    }


def correct_texts(texts: List[str], batch_size: int = 16) -> List[Dict[str, Any]]:
    """Run MacBERT on a list of texts. Uses correct_batch if available."""
    normalized = []

    has_batch = hasattr(corrector, "correct_batch")
    has_correct = hasattr(corrector, "correct")
    has_macbert_correct = hasattr(corrector, "macbert_correct")

    for start in tqdm(range(0, len(texts), batch_size), desc="MacBERT correcting"):
        batch_texts = texts[start:start + batch_size]

        if has_batch:
            raw_results = corrector.correct_batch(batch_texts)
            # Some versions return a single dict for one input; force list.
            if isinstance(raw_results, dict):
                raw_results = [raw_results]
            for src, res in zip(batch_texts, raw_results):
                normalized.append(normalize_corrector_result(src, res))

        else:
            for src in batch_texts:
                if has_correct:
                    res = corrector.correct(src)
                elif has_macbert_correct:
                    res = corrector.macbert_correct(src)
                else:
                    raise AttributeError("MacBertCorrector has neither correct_batch, correct, nor macbert_correct.")
                normalized.append(normalize_corrector_result(src, res))

    return normalized

# ============================================================
# 5. Run correction
# ============================================================

texts = all_df["sentence_for_macbert"].tolist()
results = correct_texts(texts, batch_size=16)

if len(results) != len(all_df):
    raise RuntimeError(f"Result length mismatch: got {len(results)} results for {len(all_df)} sentences")

all_df["macbert_corrected"] = [r["corrected"] for r in results]
all_df["macbert_errors_json"] = [json.dumps(r["errors"], ensure_ascii=False) for r in results]
all_df["macbert_num_errors"] = [r["num_errors"] for r in results]
all_df["macbert_accepted_no_edit"] = [r["accepted_no_edit"] for r in results]
all_df["macbert_predicted_error"] = ~all_df["macbert_accepted_no_edit"]

# ============================================================
# 6. Metrics
# ============================================================

N = len(all_df)
gold_error = all_df["gold_is_error"]
pred_error = all_df["macbert_predicted_error"]

TP = int((gold_error & pred_error).sum())      # infelicitous and flagged
FN = int((gold_error & ~pred_error).sum())     # infelicitous but accepted: miss
TN = int((~gold_error & ~pred_error).sum())    # felicitous and accepted
FP = int((~gold_error & pred_error).sum())     # felicitous but flagged

inf_n = TP + FN
fel_n = TN + FP

summary_rows = []

def safe_div(a: float, b: float) -> float:
    return float(a / b) if b else float("nan")

summary_rows.append({
    "metric_scope": "all_400_contextual_target_sentences",
    "N": N,
    "TP_infeli_flagged": TP,
    "FN_infeli_accepted_miss": FN,
    "TN_felicitous_accepted": TN,
    "FP_felicitous_flagged": FP,
    "binary_error_detection_accuracy": safe_div(TP + TN, N),
    "miss_rate_on_infeli": safe_div(FN, inf_n),
    "detection_accuracy_on_infeli": safe_div(TP, inf_n),
    "false_positive_rate_on_felicitous": safe_div(FP, fel_n),
    "acceptance_rate_on_felicitous": safe_div(TN, fel_n),
})

for context_pref in ["BA-preferred", "SVO-preferred"]:
    sub = all_df[all_df["source_context_preference"].eq(context_pref)].copy()
    ge = sub["gold_is_error"]
    pe = sub["macbert_predicted_error"]
    tp = int((ge & pe).sum())
    fn = int((ge & ~pe).sum())
    tn = int((~ge & ~pe).sum())
    fp = int((~ge & pe).sum())
    n = len(sub)
    inf = tp + fn
    fel = tn + fp
    summary_rows.append({
        "metric_scope": context_pref,
        "N": n,
        "TP_infeli_flagged": tp,
        "FN_infeli_accepted_miss": fn,
        "TN_felicitous_accepted": tn,
        "FP_felicitous_flagged": fp,
        "binary_error_detection_accuracy": safe_div(tp + tn, n),
        "miss_rate_on_infeli": safe_div(fn, inf),
        "detection_accuracy_on_infeli": safe_div(tp, inf),
        "false_positive_rate_on_felicitous": safe_div(fp, fel),
        "acceptance_rate_on_felicitous": safe_div(tn, fel),
    })

summary_df = pd.DataFrame(summary_rows)

# Pair-level results: one pair has one preferred and one non-preferred continuation.
pair_rows = []
for pair_id, g in all_df.groupby("pair_id", sort=False):
    if len(g) != 2:
        print(f"[Warning] pair_id={pair_id} has {len(g)} rows; expected 2")
    pref = g[g["preference_in_source_context"].eq("preferred")]
    nonpref = g[g["preference_in_source_context"].eq("non-preferred")]
    if len(pref) == 0 or len(nonpref) == 0:
        continue
    pref_row = pref.iloc[0]
    nonpref_row = nonpref.iloc[0]
    pair_rows.append({
        "pair_id": pair_id,
        "source_context_preference": pref_row["source_context_preference"],
        "preferred_candidate": pref_row["construction_candidate"],
        "nonpreferred_candidate": nonpref_row["construction_candidate"],
        "preferred_sentence": pref_row["full_test_sentence"],
        "nonpreferred_sentence": nonpref_row["full_test_sentence"],
        "preferred_accepted": bool(pref_row["macbert_accepted_no_edit"]),
        "nonpreferred_flagged": bool(nonpref_row["macbert_predicted_error"]),
        "pair_pragmatic_correction_correct": bool(pref_row["macbert_accepted_no_edit"] and nonpref_row["macbert_predicted_error"]),
        "nonpreferred_missed": bool(nonpref_row["macbert_accepted_no_edit"]),
        "preferred_errors_json": pref_row["macbert_errors_json"],
        "nonpreferred_errors_json": nonpref_row["macbert_errors_json"],
    })

pair_df = pd.DataFrame(pair_rows)

pair_summary_rows = []
for scope_name, sub in [("all_200_pairs", pair_df)]:
    pair_summary_rows.append({
        "metric_scope": scope_name,
        "N_pairs": len(sub),
        "pair_pragmatic_correction_accuracy": safe_div(sub["pair_pragmatic_correction_correct"].sum(), len(sub)),
        "pair_nonpreferred_miss_rate": safe_div(sub["nonpreferred_missed"].sum(), len(sub)),
        "pair_nonpreferred_detection_rate": safe_div(sub["nonpreferred_flagged"].sum(), len(sub)),
        "preferred_acceptance_rate": safe_div(sub["preferred_accepted"].sum(), len(sub)),
    })

for context_pref in ["BA-preferred", "SVO-preferred"]:
    sub = pair_df[pair_df["source_context_preference"].eq(context_pref)]
    pair_summary_rows.append({
        "metric_scope": context_pref + "_pairs",
        "N_pairs": len(sub),
        "pair_pragmatic_correction_accuracy": safe_div(sub["pair_pragmatic_correction_correct"].sum(), len(sub)),
        "pair_nonpreferred_miss_rate": safe_div(sub["nonpreferred_missed"].sum(), len(sub)),
        "pair_nonpreferred_detection_rate": safe_div(sub["nonpreferred_flagged"].sum(), len(sub)),
        "preferred_acceptance_rate": safe_div(sub["preferred_accepted"].sum(), len(sub)),
    })

pair_summary_df = pd.DataFrame(pair_summary_rows)

# ============================================================
# 7. Save outputs
# ============================================================

all_results_path = os.path.join(OUTPUT_DIR, "macbert_all_400_sentence_results.csv")
summary_path = os.path.join(OUTPUT_DIR, "macbert_summary_metrics.csv")
pair_results_path = os.path.join(OUTPUT_DIR, "macbert_pair_level_results.csv")
pair_summary_path = os.path.join(OUTPUT_DIR, "macbert_pair_summary_metrics.csv")

all_df.to_csv(all_results_path, index=False, encoding="utf-8-sig")
summary_df.to_csv(summary_path, index=False, encoding="utf-8-sig")
pair_df.to_csv(pair_results_path, index=False, encoding="utf-8-sig")
pair_summary_df.to_csv(pair_summary_path, index=False, encoding="utf-8-sig")

print("\n================ Sentence-level summary ================")
print(summary_df.to_string(index=False))

print("\n================ Pair-level summary ================")
print(pair_summary_df.to_string(index=False))

print("\nSaved files:")
for p in [all_results_path, summary_path, pair_results_path, pair_summary_path]:
    print(" -", p)

# Zip outputs for download.
zip_path = "/content/macbert_baseline_results.zip"
with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
    for p in [all_results_path, summary_path, pair_results_path, pair_summary_path]:
        zf.write(p, arcname=os.path.basename(p))

print("\nZIP:", zip_path)

try:
    from google.colab import files
    files.download(zip_path)
except Exception:
    print("If automatic download does not start, download the ZIP manually from the Colab file panel.")

import re
import pandas as pd

import pandas as pd

sent = pd.read_csv("macbert_baseline_results/macbert_all_400_sentence_results.csv")
pairs = pd.read_csv("macbert_baseline_results/macbert_pair_level_results.csv")

def norm(x):
    x = str(x)
    x = re.sub(r"[\s。.!！?？，,]", "", x)
    return x

inf = sent[sent["gold_label"] == "infelicitous"].copy()
inf = inf.merge(
    pairs[["pair_id", "preferred_sentence", "nonpreferred_sentence"]],
    on="pair_id",
    how="left"
)

inf["corrected_to_preferred"] = inf.apply(
    lambda r: norm(r["macbert_corrected"]) == norm(r["preferred_sentence"]),
    axis=1
)

construction_level_acc = inf["corrected_to_preferred"].mean()
construction_level_miss = 1 - construction_level_acc

print(f"Construction-level correction accuracy: {construction_level_acc:.2%}")
print(f"Construction-level miss rate: {construction_level_miss:.2%}")
print(f"N infelicitous continuations: {len(inf)}")
print(f"N corrected to preferred: {inf['corrected_to_preferred'].sum()}")